export type Verse = { text: string; reference: string };

/**
 * Versículos na versão Almeida Revista e Corrigida (ARC), selecionados em torno
 * de 5 temas: encorajamento, refrigério/descanso, criação, juventude e Deus
 * como Pai. Lista grande o bastante pra minimizar repetição ao longo do ano.
 */
const VERSES: Verse[] = [
  { text: "Tudo posso naquele que me fortalece.", reference: "Filipenses 4:13" },
  { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo.", reference: "Isaías 41:10" },
  { text: "Esforça-te, e tem bom ânimo; não temas, nem te espantes, porque o Senhor teu Deus é contigo, por onde quer que andares.", reference: "Josué 1:9" },
  { text: "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.", reference: "Isaías 40:31" },
  { text: "Sede fortes e corajosos; não temais, nem vos assombreis diante deles, porque o Senhor teu Deus é o que vai contigo.", reference: "Deuteronômio 31:6" },
  { text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.", reference: "2 Timóteo 1:7" },
  { text: "O Senhor é a minha luz e a minha salvação; a quem temerei?", reference: "Salmos 27:1" },
  { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", reference: "Salmos 46:1" },
  { text: "Se Deus é por nós, quem será contra nós?", reference: "Romanos 8:31" },
  { text: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.", reference: "Romanos 8:28" },
  { text: "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desanimados; perseguidos, mas não desamparados; abatidos, mas não destruídos.", reference: "2 Coríntios 4:8-9" },
  { text: "Este é o dia que fez o Senhor; regozijemo-nos, e alegremo-nos nele.", reference: "Salmos 118:24" },
  { text: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.", reference: "Provérbios 3:5-6" },
  { text: "Porque eu, o Senhor teu Deus, te tomo pela tua mão direita, e te digo: Não temas, eu te ajudo.", reference: "Isaías 41:13" },
  { text: "Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais.", reference: "Jeremias 29:11" },
  { text: "O Senhor Jeová é a minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas.", reference: "Habacuque 3:19" },
  { text: "Os justos clamam, e o Senhor os ouve, e os livra de todas as suas angústias. Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito.", reference: "Salmos 34:17-18" },
  { text: "Levantarei os meus olhos para os montes, de onde vem o meu socorro. O meu socorro vem do Senhor, que fez o céu e a terra.", reference: "Salmos 121:1-2" },
  { text: "Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.", reference: "1 Coríntios 15:58" },
  { text: "Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera.", reference: "Efésios 3:20" },
  { text: "E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", reference: "2 Coríntios 12:9" },
  { text: "Lança a tua carga sobre o Senhor, e ele te susterá; jamais permitirá que o justo seja abalado.", reference: "Salmos 55:22" },
  { text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", reference: "1 Pedro 5:7" },
  { text: "Porque a sua ira dura só um momento; no seu favor está a vida; o choro pode durar uma noite, mas a alegria vem pela manhã.", reference: "Salmos 30:5" },
  { text: "O Senhor te abençoe, e te guarde; o Senhor faça resplandecer o seu rosto sobre ti, e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto, e te dê a paz.", reference: "Números 6:24-26" },
  { text: "Entrega o teu caminho ao Senhor; confia nele, e ele o fará.", reference: "Salmos 37:5" },
  { text: "A alegria do Senhor é a vossa força.", reference: "Neemias 8:10" },
  { text: "O Senhor aperfeiçoará o que me concerne; a tua benignidade, Senhor, dura para sempre; não abandones as obras de tuas mãos.", reference: "Salmos 138:8" },
  { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", reference: "Mateus 11:28" },
  { text: "Tomai sobre vós o meu jugo, e aprendei de mim, porque sou manso e humilde de coração; e encontrareis descanso para a vossa alma.", reference: "Mateus 11:29" },
  { text: "O Senhor é o meu pastor; nada me faltará. Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas.", reference: "Salmos 23:1-2" },
  { text: "Refrigera a minha alma; guia-me pelas veredas da justiça, por amor do seu nome.", reference: "Salmos 23:3" },
  { text: "Ele dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.", reference: "Isaías 40:29" },
  { text: "Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham assim os tempos de refrigério pela presença do Senhor.", reference: "Atos 3:19" },
  { text: "Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.", reference: "Salmos 4:8" },
  { text: "A minha alma espera somente em Deus; dele vem a minha salvação.", reference: "Salmos 62:1" },
  { text: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.", reference: "João 14:27" },
  { text: "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.", reference: "Filipenses 4:7" },
  { text: "Volta, minha alma, ao teu repouso, pois o Senhor te fez bem.", reference: "Salmos 116:7" },
  { text: "Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.", reference: "Isaías 26:3" },
  { text: "Porque saciarei a alma cansada, e encherei toda alma entristecida.", reference: "Jeremias 31:25" },
  { text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", reference: "Salmos 91:1" },
  { text: "No princípio criou Deus os céus e a terra.", reference: "Gênesis 1:1" },
  { text: "E criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou.", reference: "Gênesis 1:27" },
  { text: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos.", reference: "Salmos 19:1" },
  { text: "Eu te louvarei, porque de um modo assombroso, e maravilhoso me formaste; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.", reference: "Salmos 139:14" },
  { text: "Ó Senhor, quão variadas são as tuas obras! Em sabedoria as fizeste todas; a terra está cheia da tua riqueza.", reference: "Salmos 104:24" },
  { text: "Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.", reference: "Efésios 2:10" },
  { text: "Porque nele foram criadas todas as coisas que há nos céus e na terra, visíveis e invisíveis.", reference: "Colossenses 1:16" },
  { text: "A todos os que são chamados pelo meu nome e que criei para a minha glória.", reference: "Isaías 43:7" },
  { text: "Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.", reference: "2 Coríntios 5:17" },
  { text: "Porque o Senhor é bom, e eterna é a sua benignidade; e a sua verdade dura de geração em geração.", reference: "Salmos 100:5" },
  { text: "Quando vejo os teus céus, obra dos teus dedos, a lua e as estrelas que preparaste; que é o homem, para que te lembres dele?", reference: "Salmos 8:3-4" },
  { text: "Digno és, Senhor, de receber a glória, e a honra, e o poder; porque tu criaste todas as coisas.", reference: "Apocalipse 4:11" },
  { text: "Mas agora, Senhor, tu és nosso Pai; nós, o barro, e tu, o nosso oleiro; e todos nós, obra das tuas mãos.", reference: "Isaías 64:8" },
  { text: "Ninguém despreze a tua mocidade, mas sê o exemplo dos fiéis, na palavra, no trato, no amor, no espírito, na fé, na pureza.", reference: "1 Timóteo 4:12" },
  { text: "Lembra-te também do teu Criador nos dias da tua mocidade.", reference: "Eclesiastes 12:1" },
  { text: "Com que purificará o jovem o seu caminho? Guardando-se conforme a tua palavra.", reference: "Salmos 119:9" },
  { text: "Ensina a criança no caminho em que deve andar, e ainda quando for velho não se desviará dele.", reference: "Provérbios 22:6" },
  { text: "Não digas: Sou uma criança; porque a todos os que eu te enviar, irás, e tudo quanto te mandar, dirás.", reference: "Jeremias 1:7" },
  { text: "Escrevo-vos, jovens, porque sois fortes, e a palavra de Deus permanece em vós, e já vencestes o maligno.", reference: "1 João 2:14" },
  { text: "Exorta semelhantemente os jovens a que sejam moderados.", reference: "Tito 2:6" },
  { text: "Os moços e as donzelas, os velhos e as crianças louvem o nome do Senhor.", reference: "Salmos 148:12-13" },
  { text: "Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome.", reference: "Mateus 6:9" },
  { text: "Porque não recebestes o espírito de escravidão, para outra vez estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.", reference: "Romanos 8:15" },
  { text: "Se vós, pois, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais vosso Pai, que está nos céus, dará bens aos que lhos pedirem?", reference: "Mateus 7:11" },
  { text: "Vede que grande amor nos tem concedido o Pai, que fôssemos chamados filhos de Deus.", reference: "1 João 3:1" },
  { text: "Pai de órfãos e juiz de viúvas é Deus no seu santo habitáculo.", reference: "Salmos 68:5" },
  { text: "Olhai para as aves do céu, que nem semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta.", reference: "Mateus 6:26" },
  { text: "Se vós, pois, sendo maus, sabeis dar boas dádivas a vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?", reference: "Lucas 11:13" },
  { text: "E, porque sois filhos, Deus enviou aos vossos corações o Espírito de seu Filho, que clama: Aba, Pai.", reference: "Gálatas 4:6" },
  { text: "Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem.", reference: "Salmos 103:13" },
  { text: "Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, aos que crêem no seu nome.", reference: "João 1:12" },
  { text: "E nos predestinou para filhos de adoção por Jesus Cristo, para si mesmo, segundo o beneplácito de sua vontade.", reference: "Efésios 1:5" },
  { text: "Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti levanto a minha alma.", reference: "Salmos 143:8" },
  { text: "As misericórdias do Senhor são a causa de não sermos consumidos; porque as suas misericórdias não têm fim; renovam-se cada manhã. Grande é a tua fidelidade.", reference: "Lamentações 3:22-23" },
  { text: "Bom é louvar ao Senhor, e cantar louvores ao teu nome, ó Altíssimo; anunciar de manhã a tua benignidade, e de noite a tua fidelidade.", reference: "Salmos 92:1-2" },
  { text: "Confia ao Senhor as tuas obras, e teus pensamentos serão bem-sucedidos.", reference: "Provérbios 16:3" },
  { text: "E seja sobre nós a formosura do Senhor nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.", reference: "Salmos 90:17" },
  { text: "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.", reference: "Provérbios 3:6" },
  { text: "Tu me farás ver a vereda da vida; na tua presença há fartura de alegria; à tua mão direita há delícias perpetuamente.", reference: "Salmos 16:11" },
  { text: "Eu sou a videira, vós as varas; quem está em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer.", reference: "João 15:5" },
  { text: "E não nos cansemos de fazer o bem, pois a seu tempo ceifaremos, se não houvermos desfalecido.", reference: "Gálatas 6:9" },
  { text: "O justo florescerá como a palmeira; os que estão plantados na casa do Senhor florescerão nos átrios do nosso Deus. Na velhice ainda darão frutos.", reference: "Salmos 92:12-14" },
  { text: "E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.", reference: "Colossenses 3:23" },
  { text: "Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus.", reference: "1 Coríntios 3:9" },
  { text: "Pela palavra do Senhor foram feitos os céus, e todo o exército deles pelo espírito da sua boca.", reference: "Salmos 33:6" },
  { text: "Mas a vereda dos justos é como a luz da alva, que vai brilhando mais e mais até ser dia perfeito.", reference: "Provérbios 4:18" },
  { text: "O Senhor teu Deus está no meio de ti, poderoso ele te salvará; ele se deleitará em ti com alegria; ele se aquietará no seu amor, ele se regozijará em ti com cânticos.", reference: "Sofonias 3:17" },
  { text: "Pois tu formaste os meus rins; cobriste-me no ventre de minha mãe.", reference: "Salmos 139:13" },
  { text: "E vos renoveis no espírito do vosso entendimento, e vos revistais do novo homem, que segundo Deus é criado em verdadeira justiça e santidade.", reference: "Efésios 4:23-24" },
  { text: "O eterno Deus é o teu refúgio, e por baixo estão os braços eternos.", reference: "Deuteronômio 33:27" },
  { text: "Porque tu és a minha esperança, Senhor Jeová, tu és a minha confiança desde a minha mocidade. Por ti tenho sido sustentado desde o ventre.", reference: "Salmos 71:5-6" },
  { text: "A glória dos jovens é a sua força, e a beleza dos velhos, as cãs.", reference: "Provérbios 20:29" },
  { text: "Por isso, não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.", reference: "2 Coríntios 4:16" },
  { text: "Sabei que o Senhor é Deus; foi ele que nos fez, e não nós a nós mesmos; somos povo seu e ovelhas do seu pasto.", reference: "Salmos 100:3" },
  { text: "O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.", reference: "Romanos 8:16" },
  { text: "Porque meu pai e minha mãe me desamparam, mas o Senhor me recolherá.", reference: "Salmos 27:10" },
  { text: "Torre forte é o nome do Senhor; a ele correrá o justo, e estará seguro.", reference: "Provérbios 18:10" },
  { text: "Mas agora, assim diz o Senhor que te criou, ó Jacó, e o que te formou, ó Israel: Não temas, porque eu te resgatei, chamei-te pelo teu nome, tu és meu.", reference: "Isaías 43:1" },
];

/** Mesmo versículo para todos o dia inteiro — rotaciona uma vez ao dia. */
export function getDailyVerse(date: Date = new Date()): Verse {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / 86_400_000);
  return VERSES[dayOfYear % VERSES.length];
}
