/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedRotinaRouteImport } from './routes/_authenticated/rotina'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhasTarefasRouteImport } from './routes/_authenticated/minhas-tarefas'
import { Route as AuthenticatedInvestigacaoRouteImport } from './routes/_authenticated/investigacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOauthDriveCallbackRouteImport } from './routes/_authenticated/oauth.drive-callback'
import { Route as AuthenticatedClienteClientIdRouteImport } from './routes/_authenticated/cliente.$clientId'

const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotinaRoute = AuthenticatedRotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasTarefasRoute =
  AuthenticatedMinhasTarefasRouteImport.update({
    id: '/minhas-tarefas',
    path: '/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigacaoRoute =
  AuthenticatedInvestigacaoRouteImport.update({
    id: '/investigacao',
    path: '/investigacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOauthDriveCallbackRoute =
  AuthenticatedOauthDriveCallbackRouteImport.update({
    id: '/oauth/drive-callback',
    path: '/oauth/drive-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteClientIdRoute =
  AuthenticatedClienteClientIdRouteImport.update({
    id: '/cliente/$clientId',
    path: '/cliente/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/_authenticated/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/rotina': typeof AuthenticatedRotinaRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/_authenticated/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/_authenticated/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/auth'
    | '/privacidade'
    | '/admin'
    | '/ajuda'
    | '/configuracoes'
    | '/investigacao'
    | '/minhas-tarefas'
    | '/perfil'
    | '/rotina'
    | '/stories'
    | '/preview/$token'
    | '/cliente/$clientId'
    | '/oauth/drive-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/auth'
    | '/privacidade'
    | '/admin'
    | '/ajuda'
    | '/configuracoes'
    | '/investigacao'
    | '/minhas-tarefas'
    | '/perfil'
    | '/rotina'
    | '/stories'
    | '/preview/$token'
    | '/cliente/$clientId'
    | '/oauth/drive-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assinar'
    | '/auth'
    | '/privacidade'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/investigacao'
    | '/_authenticated/minhas-tarefas'
    | '/_authenticated/perfil'
    | '/_authenticated/rotina'
    | '/_authenticated/stories'
    | '/preview/$token'
    | '/_authenticated/cliente/$clientId'
    | '/_authenticated/oauth/drive-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssinarRoute: typeof AssinarRoute
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotina': {
      id: '/_authenticated/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof AuthenticatedRotinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-tarefas': {
      id: '/_authenticated/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacao': {
      id: '/_authenticated/investigacao'
      path: '/investigacao'
      fullPath: '/investigacao'
      preLoaderRoute: typeof AuthenticatedInvestigacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/drive-callback': {
      id: '/_authenticated/oauth/drive-callback'
      path: '/oauth/drive-callback'
      fullPath: '/oauth/drive-callback'
      preLoaderRoute: typeof AuthenticatedOauthDriveCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/$clientId': {
      id: '/_authenticated/cliente/$clientId'
      path: '/cliente/$clientId'
      fullPath: '/cliente/$clientId'
      preLoaderRoute: typeof AuthenticatedClienteClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedInvestigacaoRoute: typeof AuthenticatedInvestigacaoRoute
  AuthenticatedMinhasTarefasRoute: typeof AuthenticatedMinhasTarefasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRotinaRoute: typeof AuthenticatedRotinaRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRoute
  AuthenticatedClienteClientIdRoute: typeof AuthenticatedClienteClientIdRoute
  AuthenticatedOauthDriveCallbackRoute: typeof AuthenticatedOauthDriveCallbackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedInvestigacaoRoute: AuthenticatedInvestigacaoRoute,
  AuthenticatedMinhasTarefasRoute: AuthenticatedMinhasTarefasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRotinaRoute: AuthenticatedRotinaRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRoute,
  AuthenticatedClienteClientIdRoute: AuthenticatedClienteClientIdRoute,
  AuthenticatedOauthDriveCallbackRoute: AuthenticatedOauthDriveCallbackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssinarRoute: AssinarRoute,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PreviewTokenRoute: PreviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
