/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelecaoDeFotosParaFotografosRouteImport } from './routes/selecao-de-fotos-para-fotografos'
import { Route as RevendaRouteImport } from './routes/revenda'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PublicacaoAutomaticaTiktokRouteImport } from './routes/publicacao-automatica-tiktok'
import { Route as PublicacaoAutomaticaInstagramRouteImport } from './routes/publicacao-automatica-instagram'
import { Route as ProgramaDeNiveisRouteImport } from './routes/programa-de-niveis'
import { Route as ProgramaDeIndicacaoRouteImport } from './routes/programa-de-indicacao'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanejamentoComIaRouteImport } from './routes/planejamento-com-ia'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BibliotecaDeReferenciasRouteImport } from './routes/biblioteca-de-referencias'
import { Route as BackupAutomaticoDriveRouteImport } from './routes/backup-automatico-drive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinaturaEletronicaDeContratosRouteImport } from './routes/assinatura-eletronica-de-contratos'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AprovacaoDeConteudoPorLinkRouteImport } from './routes/aprovacao-de-conteudo-por-link'
import { Route as AfiliarRouteImport } from './routes/afiliar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelecaoTokenRouteImport } from './routes/selecao.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PromoSlugRouteImport } from './routes/promo/$slug'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as PlanejamentoTokenRouteImport } from './routes/planejamento.$token'
import { Route as OauthInstagramCallbackClienteRouteImport } from './routes/oauth.instagram-callback-cliente'
import { Route as InsightsTokenRouteImport } from './routes/insights.$token'
import { Route as HouseCriarRouteImport } from './routes/house.criar'
import { Route as ContratoTokenRouteImport } from './routes/contrato.$token'
import { Route as ConectarInstagramTokenRouteImport } from './routes/conectar-instagram.$token'
import { Route as CampanhaTokenRouteImport } from './routes/campanha.$token'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AssinarCompletarRouteImport } from './routes/assinar_.completar'
import { Route as ApiPublicDriveFileRouteImport } from './routes/api.public-drive-file'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedSelecaoDeFotosRouteImport } from './routes/_authenticated/selecao-de-fotos'
import { Route as AuthenticatedRotinaRouteImport } from './routes/_authenticated/rotina'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMinhasTarefasRouteImport } from './routes/_authenticated/minhas-tarefas'
import { Route as AuthenticatedMeuDiaRouteImport } from './routes/_authenticated/meu-dia'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInstagramRouteImport } from './routes/_authenticated/instagram'
import { Route as AuthenticatedFuncionalidadesRouteImport } from './routes/_authenticated/funcionalidades'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedBaseModeloRouteImport } from './routes/_authenticated/base-modelo'
import { Route as AuthenticatedAvulsosRouteImport } from './routes/_authenticated/avulsos'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as ApiSelecaoOgTokenRouteImport } from './routes/api.selecao-og.$token'
import { Route as ApiIgMediaTokenRouteImport } from './routes/api.ig-media.$token'
import { Route as ApiDescadastrarTokenRouteImport } from './routes/api.descadastrar.$token'
import { Route as ApiCronSnapshotInstagramFollowersRouteImport } from './routes/api.cron.snapshot-instagram-followers'
import { Route as ApiCronSendPushNotificationsRouteImport } from './routes/api.cron.send-push-notifications'
import { Route as ApiCronSendAutomationEmailsRouteImport } from './routes/api.cron.send-automation-emails'
import { Route as ApiCronRetentionCleanupRouteImport } from './routes/api.cron.retention-cleanup'
import { Route as ApiCronRefreshInstagramTokensRouteImport } from './routes/api.cron.refresh-instagram-tokens'
import { Route as ApiCronPublishTiktokRouteImport } from './routes/api.cron.publish-tiktok'
import { Route as ApiCronPublishLinkedinRouteImport } from './routes/api.cron.publish-linkedin'
import { Route as ApiCronPublishInstagramRouteImport } from './routes/api.cron.publish-instagram'
import { Route as ApiCronPublishFacebookRouteImport } from './routes/api.cron.publish-facebook'
import { Route as ApiCronHouseDailyStatsRouteImport } from './routes/api.cron.house-daily-stats'
import { Route as ApiCronComputeAgencyRanksRouteImport } from './routes/api.cron.compute-agency-ranks'
import { Route as ApiCronCheckAgencyReferralsRouteImport } from './routes/api.cron.check-agency-referrals'
import { Route as ApiCronActivationNudgesRouteImport } from './routes/api.cron.activation-nudges'
import { Route as AuthenticatedSelecaoDeFotosClientIdRouteImport } from './routes/_authenticated/selecao-de-fotos_.$clientId'
import { Route as AuthenticatedOauthTiktokCallbackRouteImport } from './routes/_authenticated/oauth.tiktok-callback'
import { Route as AuthenticatedOauthLinkedinCallbackRouteImport } from './routes/_authenticated/oauth.linkedin-callback'
import { Route as AuthenticatedOauthInstagramCallbackRouteImport } from './routes/_authenticated/oauth.instagram-callback'
import { Route as AuthenticatedOauthGoogleCalendarCallbackRouteImport } from './routes/_authenticated/oauth.google-calendar-callback'
import { Route as AuthenticatedOauthFacebookCallbackRouteImport } from './routes/_authenticated/oauth.facebook-callback'
import { Route as AuthenticatedOauthDriveCallbackRouteImport } from './routes/_authenticated/oauth.drive-callback'
import { Route as AuthenticatedClienteClientIdRouteImport } from './routes/_authenticated/cliente.$clientId'
import { Route as AuthenticatedAfiliadoDashboardRouteImport } from './routes/_authenticated/afiliado/dashboard'
import { Route as ApiSelecaoDownloadTokenFileIdRouteImport } from './routes/api.selecao-download.$token.$fileId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecaoDeFotosParaFotografosRoute =
  SelecaoDeFotosParaFotografosRouteImport.update({
    id: '/selecao-de-fotos-para-fotografos',
    path: '/selecao-de-fotos-para-fotografos',
    getParentRoute: () => rootRouteImport,
  } as any)
const RevendaRoute = RevendaRouteImport.update({
  id: '/revenda',
  path: '/revenda',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacaoAutomaticaTiktokRoute =
  PublicacaoAutomaticaTiktokRouteImport.update({
    id: '/publicacao-automatica-tiktok',
    path: '/publicacao-automatica-tiktok',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicacaoAutomaticaInstagramRoute =
  PublicacaoAutomaticaInstagramRouteImport.update({
    id: '/publicacao-automatica-instagram',
    path: '/publicacao-automatica-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramaDeNiveisRoute = ProgramaDeNiveisRouteImport.update({
  id: '/programa-de-niveis',
  path: '/programa-de-niveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaDeIndicacaoRoute = ProgramaDeIndicacaoRouteImport.update({
  id: '/programa-de-indicacao',
  path: '/programa-de-indicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoComIaRoute = PlanejamentoComIaRouteImport.update({
  id: '/planejamento-com-ia',
  path: '/planejamento-com-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaDeReferenciasRoute = BibliotecaDeReferenciasRouteImport.update({
  id: '/biblioteca-de-referencias',
  path: '/biblioteca-de-referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupAutomaticoDriveRoute = BackupAutomaticoDriveRouteImport.update({
  id: '/backup-automatico-drive',
  path: '/backup-automatico-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaEletronicaDeContratosRoute =
  AssinaturaEletronicaDeContratosRouteImport.update({
    id: '/assinatura-eletronica-de-contratos',
    path: '/assinatura-eletronica-de-contratos',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacaoDeConteudoPorLinkRoute =
  AprovacaoDeConteudoPorLinkRouteImport.update({
    id: '/aprovacao-de-conteudo-por-link',
    path: '/aprovacao-de-conteudo-por-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const AfiliarRoute = AfiliarRouteImport.update({
  id: '/afiliar',
  path: '/afiliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecaoTokenRoute = SelecaoTokenRouteImport.update({
  id: '/selecao/$token',
  path: '/selecao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoSlugRoute = PromoSlugRouteImport.update({
  id: '/promo/$slug',
  path: '/promo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoTokenRoute = PlanejamentoTokenRouteImport.update({
  id: '/planejamento/$token',
  path: '/planejamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthInstagramCallbackClienteRoute =
  OauthInstagramCallbackClienteRouteImport.update({
    id: '/oauth/instagram-callback-cliente',
    path: '/oauth/instagram-callback-cliente',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsTokenRoute = InsightsTokenRouteImport.update({
  id: '/insights/$token',
  path: '/insights/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseCriarRoute = HouseCriarRouteImport.update({
  id: '/house/criar',
  path: '/house/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoTokenRoute = ContratoTokenRouteImport.update({
  id: '/contrato/$token',
  path: '/contrato/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarInstagramTokenRoute = ConectarInstagramTokenRouteImport.update({
  id: '/conectar-instagram/$token',
  path: '/conectar-instagram/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhaTokenRoute = CampanhaTokenRouteImport.update({
  id: '/campanha/$token',
  path: '/campanha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarCompletarRoute = AssinarCompletarRouteImport.update({
  id: '/assinar_/completar',
  path: '/assinar/completar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveFileRoute = ApiPublicDriveFileRouteImport.update({
  id: '/api/public-drive-file',
  path: '/api/public-drive-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelecaoDeFotosRoute =
  AuthenticatedSelecaoDeFotosRouteImport.update({
    id: '/selecao-de-fotos',
    path: '/selecao-de-fotos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotinaRoute = AuthenticatedRotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasTarefasRoute =
  AuthenticatedMinhasTarefasRouteImport.update({
    id: '/minhas-tarefas',
    path: '/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuDiaRoute = AuthenticatedMeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramRoute = AuthenticatedInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionalidadesRoute =
  AuthenticatedFuncionalidadesRouteImport.update({
    id: '/funcionalidades',
    path: '/funcionalidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseModeloRoute = AuthenticatedBaseModeloRouteImport.update({
  id: '/base-modelo',
  path: '/base-modelo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvulsosRoute = AuthenticatedAvulsosRouteImport.update({
  id: '/avulsos',
  path: '/avulsos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelecaoOgTokenRoute = ApiSelecaoOgTokenRouteImport.update({
  id: '/api/selecao-og/$token',
  path: '/api/selecao-og/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIgMediaTokenRoute = ApiIgMediaTokenRouteImport.update({
  id: '/api/ig-media/$token',
  path: '/api/ig-media/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDescadastrarTokenRoute = ApiDescadastrarTokenRouteImport.update({
  id: '/api/descadastrar/$token',
  path: '/api/descadastrar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSnapshotInstagramFollowersRoute =
  ApiCronSnapshotInstagramFollowersRouteImport.update({
    id: '/api/cron/snapshot-instagram-followers',
    path: '/api/cron/snapshot-instagram-followers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSendPushNotificationsRoute =
  ApiCronSendPushNotificationsRouteImport.update({
    id: '/api/cron/send-push-notifications',
    path: '/api/cron/send-push-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSendAutomationEmailsRoute =
  ApiCronSendAutomationEmailsRouteImport.update({
    id: '/api/cron/send-automation-emails',
    path: '/api/cron/send-automation-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronRetentionCleanupRoute = ApiCronRetentionCleanupRouteImport.update({
  id: '/api/cron/retention-cleanup',
  path: '/api/cron/retention-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshInstagramTokensRoute =
  ApiCronRefreshInstagramTokensRouteImport.update({
    id: '/api/cron/refresh-instagram-tokens',
    path: '/api/cron/refresh-instagram-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronPublishTiktokRoute = ApiCronPublishTiktokRouteImport.update({
  id: '/api/cron/publish-tiktok',
  path: '/api/cron/publish-tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishLinkedinRoute = ApiCronPublishLinkedinRouteImport.update({
  id: '/api/cron/publish-linkedin',
  path: '/api/cron/publish-linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishInstagramRoute = ApiCronPublishInstagramRouteImport.update({
  id: '/api/cron/publish-instagram',
  path: '/api/cron/publish-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishFacebookRoute = ApiCronPublishFacebookRouteImport.update({
  id: '/api/cron/publish-facebook',
  path: '/api/cron/publish-facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronHouseDailyStatsRoute = ApiCronHouseDailyStatsRouteImport.update({
  id: '/api/cron/house-daily-stats',
  path: '/api/cron/house-daily-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronComputeAgencyRanksRoute =
  ApiCronComputeAgencyRanksRouteImport.update({
    id: '/api/cron/compute-agency-ranks',
    path: '/api/cron/compute-agency-ranks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronCheckAgencyReferralsRoute =
  ApiCronCheckAgencyReferralsRouteImport.update({
    id: '/api/cron/check-agency-referrals',
    path: '/api/cron/check-agency-referrals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronActivationNudgesRoute = ApiCronActivationNudgesRouteImport.update({
  id: '/api/cron/activation-nudges',
  path: '/api/cron/activation-nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelecaoDeFotosClientIdRoute =
  AuthenticatedSelecaoDeFotosClientIdRouteImport.update({
    id: '/selecao-de-fotos_/$clientId',
    path: '/selecao-de-fotos/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthTiktokCallbackRoute =
  AuthenticatedOauthTiktokCallbackRouteImport.update({
    id: '/oauth/tiktok-callback',
    path: '/oauth/tiktok-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthLinkedinCallbackRoute =
  AuthenticatedOauthLinkedinCallbackRouteImport.update({
    id: '/oauth/linkedin-callback',
    path: '/oauth/linkedin-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthInstagramCallbackRoute =
  AuthenticatedOauthInstagramCallbackRouteImport.update({
    id: '/oauth/instagram-callback',
    path: '/oauth/instagram-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthGoogleCalendarCallbackRoute =
  AuthenticatedOauthGoogleCalendarCallbackRouteImport.update({
    id: '/oauth/google-calendar-callback',
    path: '/oauth/google-calendar-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthFacebookCallbackRoute =
  AuthenticatedOauthFacebookCallbackRouteImport.update({
    id: '/oauth/facebook-callback',
    path: '/oauth/facebook-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOauthDriveCallbackRoute =
  AuthenticatedOauthDriveCallbackRouteImport.update({
    id: '/oauth/drive-callback',
    path: '/oauth/drive-callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClienteClientIdRoute =
  AuthenticatedClienteClientIdRouteImport.update({
    id: '/cliente/$clientId',
    path: '/cliente/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAfiliadoDashboardRoute =
  AuthenticatedAfiliadoDashboardRouteImport.update({
    id: '/afiliado/dashboard',
    path: '/afiliado/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiSelecaoDownloadTokenFileIdRoute =
  ApiSelecaoDownloadTokenFileIdRouteImport.update({
    id: '/api/selecao-download/$token/$fileId',
    path: '/api/selecao-download/$token/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliar': typeof AfiliarRoute
  '/aprovacao-de-conteudo-por-link': typeof AprovacaoDeConteudoPorLinkRoute
  '/assinar': typeof AssinarRoute
  '/assinatura-eletronica-de-contratos': typeof AssinaturaEletronicaDeContratosRoute
  '/auth': typeof AuthRoute
  '/backup-automatico-drive': typeof BackupAutomaticoDriveRoute
  '/biblioteca-de-referencias': typeof BibliotecaDeReferenciasRoute
  '/blog': typeof BlogRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/mfa': typeof MfaRoute
  '/planejamento-com-ia': typeof PlanejamentoComIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programa-de-indicacao': typeof ProgramaDeIndicacaoRoute
  '/programa-de-niveis': typeof ProgramaDeNiveisRoute
  '/publicacao-automatica-instagram': typeof PublicacaoAutomaticaInstagramRoute
  '/publicacao-automatica-tiktok': typeof PublicacaoAutomaticaTiktokRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/revenda': typeof RevendaRoute
  '/selecao-de-fotos-para-fotografos': typeof SelecaoDeFotosParaFotografosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/avulsos': typeof AuthenticatedAvulsosRoute
  '/base-modelo': typeof AuthenticatedBaseModeloRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funcionalidades': typeof AuthenticatedFuncionalidadesRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/selecao-de-fotos': typeof AuthenticatedSelecaoDeFotosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public-drive-file': typeof ApiPublicDriveFileRoute
  '/assinar/completar': typeof AssinarCompletarRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/campanha/$token': typeof CampanhaTokenRoute
  '/conectar-instagram/$token': typeof ConectarInstagramTokenRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/house/criar': typeof HouseCriarRoute
  '/insights/$token': typeof InsightsTokenRoute
  '/oauth/instagram-callback-cliente': typeof OauthInstagramCallbackClienteRoute
  '/planejamento/$token': typeof PlanejamentoTokenRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/r/$code': typeof RCodeRoute
  '/selecao/$token': typeof SelecaoTokenRoute
  '/afiliado/dashboard': typeof AuthenticatedAfiliadoDashboardRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
  '/oauth/facebook-callback': typeof AuthenticatedOauthFacebookCallbackRoute
  '/oauth/google-calendar-callback': typeof AuthenticatedOauthGoogleCalendarCallbackRoute
  '/oauth/instagram-callback': typeof AuthenticatedOauthInstagramCallbackRoute
  '/oauth/linkedin-callback': typeof AuthenticatedOauthLinkedinCallbackRoute
  '/oauth/tiktok-callback': typeof AuthenticatedOauthTiktokCallbackRoute
  '/selecao-de-fotos/$clientId': typeof AuthenticatedSelecaoDeFotosClientIdRoute
  '/api/cron/activation-nudges': typeof ApiCronActivationNudgesRoute
  '/api/cron/check-agency-referrals': typeof ApiCronCheckAgencyReferralsRoute
  '/api/cron/compute-agency-ranks': typeof ApiCronComputeAgencyRanksRoute
  '/api/cron/house-daily-stats': typeof ApiCronHouseDailyStatsRoute
  '/api/cron/publish-facebook': typeof ApiCronPublishFacebookRoute
  '/api/cron/publish-instagram': typeof ApiCronPublishInstagramRoute
  '/api/cron/publish-linkedin': typeof ApiCronPublishLinkedinRoute
  '/api/cron/publish-tiktok': typeof ApiCronPublishTiktokRoute
  '/api/cron/refresh-instagram-tokens': typeof ApiCronRefreshInstagramTokensRoute
  '/api/cron/retention-cleanup': typeof ApiCronRetentionCleanupRoute
  '/api/cron/send-automation-emails': typeof ApiCronSendAutomationEmailsRoute
  '/api/cron/send-push-notifications': typeof ApiCronSendPushNotificationsRoute
  '/api/cron/snapshot-instagram-followers': typeof ApiCronSnapshotInstagramFollowersRoute
  '/api/descadastrar/$token': typeof ApiDescadastrarTokenRoute
  '/api/ig-media/$token': typeof ApiIgMediaTokenRoute
  '/api/selecao-og/$token': typeof ApiSelecaoOgTokenRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/selecao-download/$token/$fileId': typeof ApiSelecaoDownloadTokenFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliar': typeof AfiliarRoute
  '/aprovacao-de-conteudo-por-link': typeof AprovacaoDeConteudoPorLinkRoute
  '/assinar': typeof AssinarRoute
  '/assinatura-eletronica-de-contratos': typeof AssinaturaEletronicaDeContratosRoute
  '/auth': typeof AuthRoute
  '/backup-automatico-drive': typeof BackupAutomaticoDriveRoute
  '/biblioteca-de-referencias': typeof BibliotecaDeReferenciasRoute
  '/blog': typeof BlogRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/mfa': typeof MfaRoute
  '/planejamento-com-ia': typeof PlanejamentoComIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programa-de-indicacao': typeof ProgramaDeIndicacaoRoute
  '/programa-de-niveis': typeof ProgramaDeNiveisRoute
  '/publicacao-automatica-instagram': typeof PublicacaoAutomaticaInstagramRoute
  '/publicacao-automatica-tiktok': typeof PublicacaoAutomaticaTiktokRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/revenda': typeof RevendaRoute
  '/selecao-de-fotos-para-fotografos': typeof SelecaoDeFotosParaFotografosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/avulsos': typeof AuthenticatedAvulsosRoute
  '/base-modelo': typeof AuthenticatedBaseModeloRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funcionalidades': typeof AuthenticatedFuncionalidadesRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/rotina': typeof AuthenticatedRotinaRoute
  '/selecao-de-fotos': typeof AuthenticatedSelecaoDeFotosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public-drive-file': typeof ApiPublicDriveFileRoute
  '/assinar/completar': typeof AssinarCompletarRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/campanha/$token': typeof CampanhaTokenRoute
  '/conectar-instagram/$token': typeof ConectarInstagramTokenRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/house/criar': typeof HouseCriarRoute
  '/insights/$token': typeof InsightsTokenRoute
  '/oauth/instagram-callback-cliente': typeof OauthInstagramCallbackClienteRoute
  '/planejamento/$token': typeof PlanejamentoTokenRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/r/$code': typeof RCodeRoute
  '/selecao/$token': typeof SelecaoTokenRoute
  '/afiliado/dashboard': typeof AuthenticatedAfiliadoDashboardRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
  '/oauth/facebook-callback': typeof AuthenticatedOauthFacebookCallbackRoute
  '/oauth/google-calendar-callback': typeof AuthenticatedOauthGoogleCalendarCallbackRoute
  '/oauth/instagram-callback': typeof AuthenticatedOauthInstagramCallbackRoute
  '/oauth/linkedin-callback': typeof AuthenticatedOauthLinkedinCallbackRoute
  '/oauth/tiktok-callback': typeof AuthenticatedOauthTiktokCallbackRoute
  '/selecao-de-fotos/$clientId': typeof AuthenticatedSelecaoDeFotosClientIdRoute
  '/api/cron/activation-nudges': typeof ApiCronActivationNudgesRoute
  '/api/cron/check-agency-referrals': typeof ApiCronCheckAgencyReferralsRoute
  '/api/cron/compute-agency-ranks': typeof ApiCronComputeAgencyRanksRoute
  '/api/cron/house-daily-stats': typeof ApiCronHouseDailyStatsRoute
  '/api/cron/publish-facebook': typeof ApiCronPublishFacebookRoute
  '/api/cron/publish-instagram': typeof ApiCronPublishInstagramRoute
  '/api/cron/publish-linkedin': typeof ApiCronPublishLinkedinRoute
  '/api/cron/publish-tiktok': typeof ApiCronPublishTiktokRoute
  '/api/cron/refresh-instagram-tokens': typeof ApiCronRefreshInstagramTokensRoute
  '/api/cron/retention-cleanup': typeof ApiCronRetentionCleanupRoute
  '/api/cron/send-automation-emails': typeof ApiCronSendAutomationEmailsRoute
  '/api/cron/send-push-notifications': typeof ApiCronSendPushNotificationsRoute
  '/api/cron/snapshot-instagram-followers': typeof ApiCronSnapshotInstagramFollowersRoute
  '/api/descadastrar/$token': typeof ApiDescadastrarTokenRoute
  '/api/ig-media/$token': typeof ApiIgMediaTokenRoute
  '/api/selecao-og/$token': typeof ApiSelecaoOgTokenRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/selecao-download/$token/$fileId': typeof ApiSelecaoDownloadTokenFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afiliar': typeof AfiliarRoute
  '/aprovacao-de-conteudo-por-link': typeof AprovacaoDeConteudoPorLinkRoute
  '/assinar': typeof AssinarRoute
  '/assinatura-eletronica-de-contratos': typeof AssinaturaEletronicaDeContratosRoute
  '/auth': typeof AuthRoute
  '/backup-automatico-drive': typeof BackupAutomaticoDriveRoute
  '/biblioteca-de-referencias': typeof BibliotecaDeReferenciasRoute
  '/blog': typeof BlogRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/mfa': typeof MfaRoute
  '/planejamento-com-ia': typeof PlanejamentoComIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programa-de-indicacao': typeof ProgramaDeIndicacaoRoute
  '/programa-de-niveis': typeof ProgramaDeNiveisRoute
  '/publicacao-automatica-instagram': typeof PublicacaoAutomaticaInstagramRoute
  '/publicacao-automatica-tiktok': typeof PublicacaoAutomaticaTiktokRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/revenda': typeof RevendaRoute
  '/selecao-de-fotos-para-fotografos': typeof SelecaoDeFotosParaFotografosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/avulsos': typeof AuthenticatedAvulsosRoute
  '/_authenticated/base-modelo': typeof AuthenticatedBaseModeloRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/funcionalidades': typeof AuthenticatedFuncionalidadesRoute
  '/_authenticated/instagram': typeof AuthenticatedInstagramRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/_authenticated/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/rotina': typeof AuthenticatedRotinaRoute
  '/_authenticated/selecao-de-fotos': typeof AuthenticatedSelecaoDeFotosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public-drive-file': typeof ApiPublicDriveFileRoute
  '/assinar_/completar': typeof AssinarCompletarRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/campanha/$token': typeof CampanhaTokenRoute
  '/conectar-instagram/$token': typeof ConectarInstagramTokenRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/house/criar': typeof HouseCriarRoute
  '/insights/$token': typeof InsightsTokenRoute
  '/oauth/instagram-callback-cliente': typeof OauthInstagramCallbackClienteRoute
  '/planejamento/$token': typeof PlanejamentoTokenRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/r/$code': typeof RCodeRoute
  '/selecao/$token': typeof SelecaoTokenRoute
  '/_authenticated/afiliado/dashboard': typeof AuthenticatedAfiliadoDashboardRoute
  '/_authenticated/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
  '/_authenticated/oauth/drive-callback': typeof AuthenticatedOauthDriveCallbackRoute
  '/_authenticated/oauth/facebook-callback': typeof AuthenticatedOauthFacebookCallbackRoute
  '/_authenticated/oauth/google-calendar-callback': typeof AuthenticatedOauthGoogleCalendarCallbackRoute
  '/_authenticated/oauth/instagram-callback': typeof AuthenticatedOauthInstagramCallbackRoute
  '/_authenticated/oauth/linkedin-callback': typeof AuthenticatedOauthLinkedinCallbackRoute
  '/_authenticated/oauth/tiktok-callback': typeof AuthenticatedOauthTiktokCallbackRoute
  '/_authenticated/selecao-de-fotos_/$clientId': typeof AuthenticatedSelecaoDeFotosClientIdRoute
  '/api/cron/activation-nudges': typeof ApiCronActivationNudgesRoute
  '/api/cron/check-agency-referrals': typeof ApiCronCheckAgencyReferralsRoute
  '/api/cron/compute-agency-ranks': typeof ApiCronComputeAgencyRanksRoute
  '/api/cron/house-daily-stats': typeof ApiCronHouseDailyStatsRoute
  '/api/cron/publish-facebook': typeof ApiCronPublishFacebookRoute
  '/api/cron/publish-instagram': typeof ApiCronPublishInstagramRoute
  '/api/cron/publish-linkedin': typeof ApiCronPublishLinkedinRoute
  '/api/cron/publish-tiktok': typeof ApiCronPublishTiktokRoute
  '/api/cron/refresh-instagram-tokens': typeof ApiCronRefreshInstagramTokensRoute
  '/api/cron/retention-cleanup': typeof ApiCronRetentionCleanupRoute
  '/api/cron/send-automation-emails': typeof ApiCronSendAutomationEmailsRoute
  '/api/cron/send-push-notifications': typeof ApiCronSendPushNotificationsRoute
  '/api/cron/snapshot-instagram-followers': typeof ApiCronSnapshotInstagramFollowersRoute
  '/api/descadastrar/$token': typeof ApiDescadastrarTokenRoute
  '/api/ig-media/$token': typeof ApiIgMediaTokenRoute
  '/api/selecao-og/$token': typeof ApiSelecaoOgTokenRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/api/selecao-download/$token/$fileId': typeof ApiSelecaoDownloadTokenFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliar'
    | '/aprovacao-de-conteudo-por-link'
    | '/assinar'
    | '/assinatura-eletronica-de-contratos'
    | '/auth'
    | '/backup-automatico-drive'
    | '/biblioteca-de-referencias'
    | '/blog'
    | '/exclusao-de-dados'
    | '/mfa'
    | '/planejamento-com-ia'
    | '/privacidade'
    | '/programa-de-indicacao'
    | '/programa-de-niveis'
    | '/publicacao-automatica-instagram'
    | '/publicacao-automatica-tiktok'
    | '/redefinir-senha'
    | '/revenda'
    | '/selecao-de-fotos-para-fotografos'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/ajuda'
    | '/avulsos'
    | '/base-modelo'
    | '/biblioteca'
    | '/calendario'
    | '/configuracoes'
    | '/demandas'
    | '/financeiro'
    | '/funcionalidades'
    | '/instagram'
    | '/leads'
    | '/lixeira'
    | '/meu-dia'
    | '/minhas-tarefas'
    | '/painel'
    | '/perfil'
    | '/playbook'
    | '/projetos'
    | '/relatorio'
    | '/rotina'
    | '/selecao-de-fotos'
    | '/vendas'
    | '/api/mcp'
    | '/api/public-drive-file'
    | '/assinar/completar'
    | '/blog/$slug'
    | '/campanha/$token'
    | '/conectar-instagram/$token'
    | '/contrato/$token'
    | '/house/criar'
    | '/insights/$token'
    | '/oauth/instagram-callback-cliente'
    | '/planejamento/$token'
    | '/preview/$token'
    | '/promo/$slug'
    | '/r/$code'
    | '/selecao/$token'
    | '/afiliado/dashboard'
    | '/cliente/$clientId'
    | '/oauth/drive-callback'
    | '/oauth/facebook-callback'
    | '/oauth/google-calendar-callback'
    | '/oauth/instagram-callback'
    | '/oauth/linkedin-callback'
    | '/oauth/tiktok-callback'
    | '/selecao-de-fotos/$clientId'
    | '/api/cron/activation-nudges'
    | '/api/cron/check-agency-referrals'
    | '/api/cron/compute-agency-ranks'
    | '/api/cron/house-daily-stats'
    | '/api/cron/publish-facebook'
    | '/api/cron/publish-instagram'
    | '/api/cron/publish-linkedin'
    | '/api/cron/publish-tiktok'
    | '/api/cron/refresh-instagram-tokens'
    | '/api/cron/retention-cleanup'
    | '/api/cron/send-automation-emails'
    | '/api/cron/send-push-notifications'
    | '/api/cron/snapshot-instagram-followers'
    | '/api/descadastrar/$token'
    | '/api/ig-media/$token'
    | '/api/selecao-og/$token'
    | '/api/whatsapp/webhook'
    | '/api/selecao-download/$token/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliar'
    | '/aprovacao-de-conteudo-por-link'
    | '/assinar'
    | '/assinatura-eletronica-de-contratos'
    | '/auth'
    | '/backup-automatico-drive'
    | '/biblioteca-de-referencias'
    | '/blog'
    | '/exclusao-de-dados'
    | '/mfa'
    | '/planejamento-com-ia'
    | '/privacidade'
    | '/programa-de-indicacao'
    | '/programa-de-niveis'
    | '/publicacao-automatica-instagram'
    | '/publicacao-automatica-tiktok'
    | '/redefinir-senha'
    | '/revenda'
    | '/selecao-de-fotos-para-fotografos'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/ajuda'
    | '/avulsos'
    | '/base-modelo'
    | '/biblioteca'
    | '/calendario'
    | '/configuracoes'
    | '/demandas'
    | '/financeiro'
    | '/funcionalidades'
    | '/instagram'
    | '/leads'
    | '/lixeira'
    | '/meu-dia'
    | '/minhas-tarefas'
    | '/painel'
    | '/perfil'
    | '/playbook'
    | '/projetos'
    | '/relatorio'
    | '/rotina'
    | '/selecao-de-fotos'
    | '/vendas'
    | '/api/mcp'
    | '/api/public-drive-file'
    | '/assinar/completar'
    | '/blog/$slug'
    | '/campanha/$token'
    | '/conectar-instagram/$token'
    | '/contrato/$token'
    | '/house/criar'
    | '/insights/$token'
    | '/oauth/instagram-callback-cliente'
    | '/planejamento/$token'
    | '/preview/$token'
    | '/promo/$slug'
    | '/r/$code'
    | '/selecao/$token'
    | '/afiliado/dashboard'
    | '/cliente/$clientId'
    | '/oauth/drive-callback'
    | '/oauth/facebook-callback'
    | '/oauth/google-calendar-callback'
    | '/oauth/instagram-callback'
    | '/oauth/linkedin-callback'
    | '/oauth/tiktok-callback'
    | '/selecao-de-fotos/$clientId'
    | '/api/cron/activation-nudges'
    | '/api/cron/check-agency-referrals'
    | '/api/cron/compute-agency-ranks'
    | '/api/cron/house-daily-stats'
    | '/api/cron/publish-facebook'
    | '/api/cron/publish-instagram'
    | '/api/cron/publish-linkedin'
    | '/api/cron/publish-tiktok'
    | '/api/cron/refresh-instagram-tokens'
    | '/api/cron/retention-cleanup'
    | '/api/cron/send-automation-emails'
    | '/api/cron/send-push-notifications'
    | '/api/cron/snapshot-instagram-followers'
    | '/api/descadastrar/$token'
    | '/api/ig-media/$token'
    | '/api/selecao-og/$token'
    | '/api/whatsapp/webhook'
    | '/api/selecao-download/$token/$fileId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afiliar'
    | '/aprovacao-de-conteudo-por-link'
    | '/assinar'
    | '/assinatura-eletronica-de-contratos'
    | '/auth'
    | '/backup-automatico-drive'
    | '/biblioteca-de-referencias'
    | '/blog'
    | '/exclusao-de-dados'
    | '/mfa'
    | '/planejamento-com-ia'
    | '/privacidade'
    | '/programa-de-indicacao'
    | '/programa-de-niveis'
    | '/publicacao-automatica-instagram'
    | '/publicacao-automatica-tiktok'
    | '/redefinir-senha'
    | '/revenda'
    | '/selecao-de-fotos-para-fotografos'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/avulsos'
    | '/_authenticated/base-modelo'
    | '/_authenticated/biblioteca'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracoes'
    | '/_authenticated/demandas'
    | '/_authenticated/financeiro'
    | '/_authenticated/funcionalidades'
    | '/_authenticated/instagram'
    | '/_authenticated/leads'
    | '/_authenticated/lixeira'
    | '/_authenticated/meu-dia'
    | '/_authenticated/minhas-tarefas'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/playbook'
    | '/_authenticated/projetos'
    | '/_authenticated/relatorio'
    | '/_authenticated/rotina'
    | '/_authenticated/selecao-de-fotos'
    | '/_authenticated/vendas'
    | '/api/mcp'
    | '/api/public-drive-file'
    | '/assinar_/completar'
    | '/blog_/$slug'
    | '/campanha/$token'
    | '/conectar-instagram/$token'
    | '/contrato/$token'
    | '/house/criar'
    | '/insights/$token'
    | '/oauth/instagram-callback-cliente'
    | '/planejamento/$token'
    | '/preview/$token'
    | '/promo/$slug'
    | '/r/$code'
    | '/selecao/$token'
    | '/_authenticated/afiliado/dashboard'
    | '/_authenticated/cliente/$clientId'
    | '/_authenticated/oauth/drive-callback'
    | '/_authenticated/oauth/facebook-callback'
    | '/_authenticated/oauth/google-calendar-callback'
    | '/_authenticated/oauth/instagram-callback'
    | '/_authenticated/oauth/linkedin-callback'
    | '/_authenticated/oauth/tiktok-callback'
    | '/_authenticated/selecao-de-fotos_/$clientId'
    | '/api/cron/activation-nudges'
    | '/api/cron/check-agency-referrals'
    | '/api/cron/compute-agency-ranks'
    | '/api/cron/house-daily-stats'
    | '/api/cron/publish-facebook'
    | '/api/cron/publish-instagram'
    | '/api/cron/publish-linkedin'
    | '/api/cron/publish-tiktok'
    | '/api/cron/refresh-instagram-tokens'
    | '/api/cron/retention-cleanup'
    | '/api/cron/send-automation-emails'
    | '/api/cron/send-push-notifications'
    | '/api/cron/snapshot-instagram-followers'
    | '/api/descadastrar/$token'
    | '/api/ig-media/$token'
    | '/api/selecao-og/$token'
    | '/api/whatsapp/webhook'
    | '/api/selecao-download/$token/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfiliarRoute: typeof AfiliarRoute
  AprovacaoDeConteudoPorLinkRoute: typeof AprovacaoDeConteudoPorLinkRoute
  AssinarRoute: typeof AssinarRoute
  AssinaturaEletronicaDeContratosRoute: typeof AssinaturaEletronicaDeContratosRoute
  AuthRoute: typeof AuthRoute
  BackupAutomaticoDriveRoute: typeof BackupAutomaticoDriveRoute
  BibliotecaDeReferenciasRoute: typeof BibliotecaDeReferenciasRoute
  BlogRoute: typeof BlogRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  MfaRoute: typeof MfaRoute
  PlanejamentoComIaRoute: typeof PlanejamentoComIaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgramaDeIndicacaoRoute: typeof ProgramaDeIndicacaoRoute
  ProgramaDeNiveisRoute: typeof ProgramaDeNiveisRoute
  PublicacaoAutomaticaInstagramRoute: typeof PublicacaoAutomaticaInstagramRoute
  PublicacaoAutomaticaTiktokRoute: typeof PublicacaoAutomaticaTiktokRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RevendaRoute: typeof RevendaRoute
  SelecaoDeFotosParaFotografosRoute: typeof SelecaoDeFotosParaFotografosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPublicDriveFileRoute: typeof ApiPublicDriveFileRoute
  AssinarCompletarRoute: typeof AssinarCompletarRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CampanhaTokenRoute: typeof CampanhaTokenRoute
  ConectarInstagramTokenRoute: typeof ConectarInstagramTokenRoute
  ContratoTokenRoute: typeof ContratoTokenRoute
  HouseCriarRoute: typeof HouseCriarRoute
  InsightsTokenRoute: typeof InsightsTokenRoute
  OauthInstagramCallbackClienteRoute: typeof OauthInstagramCallbackClienteRoute
  PlanejamentoTokenRoute: typeof PlanejamentoTokenRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
  PromoSlugRoute: typeof PromoSlugRoute
  RCodeRoute: typeof RCodeRoute
  SelecaoTokenRoute: typeof SelecaoTokenRoute
  ApiCronActivationNudgesRoute: typeof ApiCronActivationNudgesRoute
  ApiCronCheckAgencyReferralsRoute: typeof ApiCronCheckAgencyReferralsRoute
  ApiCronComputeAgencyRanksRoute: typeof ApiCronComputeAgencyRanksRoute
  ApiCronHouseDailyStatsRoute: typeof ApiCronHouseDailyStatsRoute
  ApiCronPublishFacebookRoute: typeof ApiCronPublishFacebookRoute
  ApiCronPublishInstagramRoute: typeof ApiCronPublishInstagramRoute
  ApiCronPublishLinkedinRoute: typeof ApiCronPublishLinkedinRoute
  ApiCronPublishTiktokRoute: typeof ApiCronPublishTiktokRoute
  ApiCronRefreshInstagramTokensRoute: typeof ApiCronRefreshInstagramTokensRoute
  ApiCronRetentionCleanupRoute: typeof ApiCronRetentionCleanupRoute
  ApiCronSendAutomationEmailsRoute: typeof ApiCronSendAutomationEmailsRoute
  ApiCronSendPushNotificationsRoute: typeof ApiCronSendPushNotificationsRoute
  ApiCronSnapshotInstagramFollowersRoute: typeof ApiCronSnapshotInstagramFollowersRoute
  ApiDescadastrarTokenRoute: typeof ApiDescadastrarTokenRoute
  ApiIgMediaTokenRoute: typeof ApiIgMediaTokenRoute
  ApiSelecaoOgTokenRoute: typeof ApiSelecaoOgTokenRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiSelecaoDownloadTokenFileIdRoute: typeof ApiSelecaoDownloadTokenFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecao-de-fotos-para-fotografos': {
      id: '/selecao-de-fotos-para-fotografos'
      path: '/selecao-de-fotos-para-fotografos'
      fullPath: '/selecao-de-fotos-para-fotografos'
      preLoaderRoute: typeof SelecaoDeFotosParaFotografosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenda': {
      id: '/revenda'
      path: '/revenda'
      fullPath: '/revenda'
      preLoaderRoute: typeof RevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacao-automatica-tiktok': {
      id: '/publicacao-automatica-tiktok'
      path: '/publicacao-automatica-tiktok'
      fullPath: '/publicacao-automatica-tiktok'
      preLoaderRoute: typeof PublicacaoAutomaticaTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacao-automatica-instagram': {
      id: '/publicacao-automatica-instagram'
      path: '/publicacao-automatica-instagram'
      fullPath: '/publicacao-automatica-instagram'
      preLoaderRoute: typeof PublicacaoAutomaticaInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-niveis': {
      id: '/programa-de-niveis'
      path: '/programa-de-niveis'
      fullPath: '/programa-de-niveis'
      preLoaderRoute: typeof ProgramaDeNiveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-indicacao': {
      id: '/programa-de-indicacao'
      path: '/programa-de-indicacao'
      fullPath: '/programa-de-indicacao'
      preLoaderRoute: typeof ProgramaDeIndicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento-com-ia': {
      id: '/planejamento-com-ia'
      path: '/planejamento-com-ia'
      fullPath: '/planejamento-com-ia'
      preLoaderRoute: typeof PlanejamentoComIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca-de-referencias': {
      id: '/biblioteca-de-referencias'
      path: '/biblioteca-de-referencias'
      fullPath: '/biblioteca-de-referencias'
      preLoaderRoute: typeof BibliotecaDeReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup-automatico-drive': {
      id: '/backup-automatico-drive'
      path: '/backup-automatico-drive'
      fullPath: '/backup-automatico-drive'
      preLoaderRoute: typeof BackupAutomaticoDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-eletronica-de-contratos': {
      id: '/assinatura-eletronica-de-contratos'
      path: '/assinatura-eletronica-de-contratos'
      fullPath: '/assinatura-eletronica-de-contratos'
      preLoaderRoute: typeof AssinaturaEletronicaDeContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacao-de-conteudo-por-link': {
      id: '/aprovacao-de-conteudo-por-link'
      path: '/aprovacao-de-conteudo-por-link'
      fullPath: '/aprovacao-de-conteudo-por-link'
      preLoaderRoute: typeof AprovacaoDeConteudoPorLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliar': {
      id: '/afiliar'
      path: '/afiliar'
      fullPath: '/afiliar'
      preLoaderRoute: typeof AfiliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecao/$token': {
      id: '/selecao/$token'
      path: '/selecao/$token'
      fullPath: '/selecao/$token'
      preLoaderRoute: typeof SelecaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/$slug': {
      id: '/promo/$slug'
      path: '/promo/$slug'
      fullPath: '/promo/$slug'
      preLoaderRoute: typeof PromoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento/$token': {
      id: '/planejamento/$token'
      path: '/planejamento/$token'
      fullPath: '/planejamento/$token'
      preLoaderRoute: typeof PlanejamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/instagram-callback-cliente': {
      id: '/oauth/instagram-callback-cliente'
      path: '/oauth/instagram-callback-cliente'
      fullPath: '/oauth/instagram-callback-cliente'
      preLoaderRoute: typeof OauthInstagramCallbackClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$token': {
      id: '/insights/$token'
      path: '/insights/$token'
      fullPath: '/insights/$token'
      preLoaderRoute: typeof InsightsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/criar': {
      id: '/house/criar'
      path: '/house/criar'
      fullPath: '/house/criar'
      preLoaderRoute: typeof HouseCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato/$token': {
      id: '/contrato/$token'
      path: '/contrato/$token'
      fullPath: '/contrato/$token'
      preLoaderRoute: typeof ContratoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar-instagram/$token': {
      id: '/conectar-instagram/$token'
      path: '/conectar-instagram/$token'
      fullPath: '/conectar-instagram/$token'
      preLoaderRoute: typeof ConectarInstagramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanha/$token': {
      id: '/campanha/$token'
      path: '/campanha/$token'
      fullPath: '/campanha/$token'
      preLoaderRoute: typeof CampanhaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar_/completar': {
      id: '/assinar_/completar'
      path: '/assinar/completar'
      fullPath: '/assinar/completar'
      preLoaderRoute: typeof AssinarCompletarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-drive-file': {
      id: '/api/public-drive-file'
      path: '/api/public-drive-file'
      fullPath: '/api/public-drive-file'
      preLoaderRoute: typeof ApiPublicDriveFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selecao-de-fotos': {
      id: '/_authenticated/selecao-de-fotos'
      path: '/selecao-de-fotos'
      fullPath: '/selecao-de-fotos'
      preLoaderRoute: typeof AuthenticatedSelecaoDeFotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotina': {
      id: '/_authenticated/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof AuthenticatedRotinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-tarefas': {
      id: '/_authenticated/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-dia': {
      id: '/_authenticated/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof AuthenticatedMeuDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram': {
      id: '/_authenticated/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AuthenticatedInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionalidades': {
      id: '/_authenticated/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof AuthenticatedFuncionalidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-modelo': {
      id: '/_authenticated/base-modelo'
      path: '/base-modelo'
      fullPath: '/base-modelo'
      preLoaderRoute: typeof AuthenticatedBaseModeloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avulsos': {
      id: '/_authenticated/avulsos'
      path: '/avulsos'
      fullPath: '/avulsos'
      preLoaderRoute: typeof AuthenticatedAvulsosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selecao-og/$token': {
      id: '/api/selecao-og/$token'
      path: '/api/selecao-og/$token'
      fullPath: '/api/selecao-og/$token'
      preLoaderRoute: typeof ApiSelecaoOgTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ig-media/$token': {
      id: '/api/ig-media/$token'
      path: '/api/ig-media/$token'
      fullPath: '/api/ig-media/$token'
      preLoaderRoute: typeof ApiIgMediaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/descadastrar/$token': {
      id: '/api/descadastrar/$token'
      path: '/api/descadastrar/$token'
      fullPath: '/api/descadastrar/$token'
      preLoaderRoute: typeof ApiDescadastrarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/snapshot-instagram-followers': {
      id: '/api/cron/snapshot-instagram-followers'
      path: '/api/cron/snapshot-instagram-followers'
      fullPath: '/api/cron/snapshot-instagram-followers'
      preLoaderRoute: typeof ApiCronSnapshotInstagramFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-push-notifications': {
      id: '/api/cron/send-push-notifications'
      path: '/api/cron/send-push-notifications'
      fullPath: '/api/cron/send-push-notifications'
      preLoaderRoute: typeof ApiCronSendPushNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/send-automation-emails': {
      id: '/api/cron/send-automation-emails'
      path: '/api/cron/send-automation-emails'
      fullPath: '/api/cron/send-automation-emails'
      preLoaderRoute: typeof ApiCronSendAutomationEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retention-cleanup': {
      id: '/api/cron/retention-cleanup'
      path: '/api/cron/retention-cleanup'
      fullPath: '/api/cron/retention-cleanup'
      preLoaderRoute: typeof ApiCronRetentionCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh-instagram-tokens': {
      id: '/api/cron/refresh-instagram-tokens'
      path: '/api/cron/refresh-instagram-tokens'
      fullPath: '/api/cron/refresh-instagram-tokens'
      preLoaderRoute: typeof ApiCronRefreshInstagramTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish-tiktok': {
      id: '/api/cron/publish-tiktok'
      path: '/api/cron/publish-tiktok'
      fullPath: '/api/cron/publish-tiktok'
      preLoaderRoute: typeof ApiCronPublishTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish-linkedin': {
      id: '/api/cron/publish-linkedin'
      path: '/api/cron/publish-linkedin'
      fullPath: '/api/cron/publish-linkedin'
      preLoaderRoute: typeof ApiCronPublishLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish-instagram': {
      id: '/api/cron/publish-instagram'
      path: '/api/cron/publish-instagram'
      fullPath: '/api/cron/publish-instagram'
      preLoaderRoute: typeof ApiCronPublishInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish-facebook': {
      id: '/api/cron/publish-facebook'
      path: '/api/cron/publish-facebook'
      fullPath: '/api/cron/publish-facebook'
      preLoaderRoute: typeof ApiCronPublishFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/house-daily-stats': {
      id: '/api/cron/house-daily-stats'
      path: '/api/cron/house-daily-stats'
      fullPath: '/api/cron/house-daily-stats'
      preLoaderRoute: typeof ApiCronHouseDailyStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/compute-agency-ranks': {
      id: '/api/cron/compute-agency-ranks'
      path: '/api/cron/compute-agency-ranks'
      fullPath: '/api/cron/compute-agency-ranks'
      preLoaderRoute: typeof ApiCronComputeAgencyRanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/check-agency-referrals': {
      id: '/api/cron/check-agency-referrals'
      path: '/api/cron/check-agency-referrals'
      fullPath: '/api/cron/check-agency-referrals'
      preLoaderRoute: typeof ApiCronCheckAgencyReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/activation-nudges': {
      id: '/api/cron/activation-nudges'
      path: '/api/cron/activation-nudges'
      fullPath: '/api/cron/activation-nudges'
      preLoaderRoute: typeof ApiCronActivationNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/selecao-de-fotos_/$clientId': {
      id: '/_authenticated/selecao-de-fotos_/$clientId'
      path: '/selecao-de-fotos/$clientId'
      fullPath: '/selecao-de-fotos/$clientId'
      preLoaderRoute: typeof AuthenticatedSelecaoDeFotosClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/tiktok-callback': {
      id: '/_authenticated/oauth/tiktok-callback'
      path: '/oauth/tiktok-callback'
      fullPath: '/oauth/tiktok-callback'
      preLoaderRoute: typeof AuthenticatedOauthTiktokCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/linkedin-callback': {
      id: '/_authenticated/oauth/linkedin-callback'
      path: '/oauth/linkedin-callback'
      fullPath: '/oauth/linkedin-callback'
      preLoaderRoute: typeof AuthenticatedOauthLinkedinCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/instagram-callback': {
      id: '/_authenticated/oauth/instagram-callback'
      path: '/oauth/instagram-callback'
      fullPath: '/oauth/instagram-callback'
      preLoaderRoute: typeof AuthenticatedOauthInstagramCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/google-calendar-callback': {
      id: '/_authenticated/oauth/google-calendar-callback'
      path: '/oauth/google-calendar-callback'
      fullPath: '/oauth/google-calendar-callback'
      preLoaderRoute: typeof AuthenticatedOauthGoogleCalendarCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/facebook-callback': {
      id: '/_authenticated/oauth/facebook-callback'
      path: '/oauth/facebook-callback'
      fullPath: '/oauth/facebook-callback'
      preLoaderRoute: typeof AuthenticatedOauthFacebookCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oauth/drive-callback': {
      id: '/_authenticated/oauth/drive-callback'
      path: '/oauth/drive-callback'
      fullPath: '/oauth/drive-callback'
      preLoaderRoute: typeof AuthenticatedOauthDriveCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/$clientId': {
      id: '/_authenticated/cliente/$clientId'
      path: '/cliente/$clientId'
      fullPath: '/cliente/$clientId'
      preLoaderRoute: typeof AuthenticatedClienteClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/afiliado/dashboard': {
      id: '/_authenticated/afiliado/dashboard'
      path: '/afiliado/dashboard'
      fullPath: '/afiliado/dashboard'
      preLoaderRoute: typeof AuthenticatedAfiliadoDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/selecao-download/$token/$fileId': {
      id: '/api/selecao-download/$token/$fileId'
      path: '/api/selecao-download/$token/$fileId'
      fullPath: '/api/selecao-download/$token/$fileId'
      preLoaderRoute: typeof ApiSelecaoDownloadTokenFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAvulsosRoute: typeof AuthenticatedAvulsosRoute
  AuthenticatedBaseModeloRoute: typeof AuthenticatedBaseModeloRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFuncionalidadesRoute: typeof AuthenticatedFuncionalidadesRoute
  AuthenticatedInstagramRoute: typeof AuthenticatedInstagramRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedMeuDiaRoute: typeof AuthenticatedMeuDiaRoute
  AuthenticatedMinhasTarefasRoute: typeof AuthenticatedMinhasTarefasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedRotinaRoute: typeof AuthenticatedRotinaRoute
  AuthenticatedSelecaoDeFotosRoute: typeof AuthenticatedSelecaoDeFotosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedAfiliadoDashboardRoute: typeof AuthenticatedAfiliadoDashboardRoute
  AuthenticatedClienteClientIdRoute: typeof AuthenticatedClienteClientIdRoute
  AuthenticatedOauthDriveCallbackRoute: typeof AuthenticatedOauthDriveCallbackRoute
  AuthenticatedOauthFacebookCallbackRoute: typeof AuthenticatedOauthFacebookCallbackRoute
  AuthenticatedOauthGoogleCalendarCallbackRoute: typeof AuthenticatedOauthGoogleCalendarCallbackRoute
  AuthenticatedOauthInstagramCallbackRoute: typeof AuthenticatedOauthInstagramCallbackRoute
  AuthenticatedOauthLinkedinCallbackRoute: typeof AuthenticatedOauthLinkedinCallbackRoute
  AuthenticatedOauthTiktokCallbackRoute: typeof AuthenticatedOauthTiktokCallbackRoute
  AuthenticatedSelecaoDeFotosClientIdRoute: typeof AuthenticatedSelecaoDeFotosClientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAvulsosRoute: AuthenticatedAvulsosRoute,
  AuthenticatedBaseModeloRoute: AuthenticatedBaseModeloRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFuncionalidadesRoute: AuthenticatedFuncionalidadesRoute,
  AuthenticatedInstagramRoute: AuthenticatedInstagramRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedMeuDiaRoute: AuthenticatedMeuDiaRoute,
  AuthenticatedMinhasTarefasRoute: AuthenticatedMinhasTarefasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedRotinaRoute: AuthenticatedRotinaRoute,
  AuthenticatedSelecaoDeFotosRoute: AuthenticatedSelecaoDeFotosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedAfiliadoDashboardRoute: AuthenticatedAfiliadoDashboardRoute,
  AuthenticatedClienteClientIdRoute: AuthenticatedClienteClientIdRoute,
  AuthenticatedOauthDriveCallbackRoute: AuthenticatedOauthDriveCallbackRoute,
  AuthenticatedOauthFacebookCallbackRoute:
    AuthenticatedOauthFacebookCallbackRoute,
  AuthenticatedOauthGoogleCalendarCallbackRoute:
    AuthenticatedOauthGoogleCalendarCallbackRoute,
  AuthenticatedOauthInstagramCallbackRoute:
    AuthenticatedOauthInstagramCallbackRoute,
  AuthenticatedOauthLinkedinCallbackRoute:
    AuthenticatedOauthLinkedinCallbackRoute,
  AuthenticatedOauthTiktokCallbackRoute: AuthenticatedOauthTiktokCallbackRoute,
  AuthenticatedSelecaoDeFotosClientIdRoute:
    AuthenticatedSelecaoDeFotosClientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfiliarRoute: AfiliarRoute,
  AprovacaoDeConteudoPorLinkRoute: AprovacaoDeConteudoPorLinkRoute,
  AssinarRoute: AssinarRoute,
  AssinaturaEletronicaDeContratosRoute: AssinaturaEletronicaDeContratosRoute,
  AuthRoute: AuthRoute,
  BackupAutomaticoDriveRoute: BackupAutomaticoDriveRoute,
  BibliotecaDeReferenciasRoute: BibliotecaDeReferenciasRoute,
  BlogRoute: BlogRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  MfaRoute: MfaRoute,
  PlanejamentoComIaRoute: PlanejamentoComIaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgramaDeIndicacaoRoute: ProgramaDeIndicacaoRoute,
  ProgramaDeNiveisRoute: ProgramaDeNiveisRoute,
  PublicacaoAutomaticaInstagramRoute: PublicacaoAutomaticaInstagramRoute,
  PublicacaoAutomaticaTiktokRoute: PublicacaoAutomaticaTiktokRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RevendaRoute: RevendaRoute,
  SelecaoDeFotosParaFotografosRoute: SelecaoDeFotosParaFotografosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPublicDriveFileRoute: ApiPublicDriveFileRoute,
  AssinarCompletarRoute: AssinarCompletarRoute,
  BlogSlugRoute: BlogSlugRoute,
  CampanhaTokenRoute: CampanhaTokenRoute,
  ConectarInstagramTokenRoute: ConectarInstagramTokenRoute,
  ContratoTokenRoute: ContratoTokenRoute,
  HouseCriarRoute: HouseCriarRoute,
  InsightsTokenRoute: InsightsTokenRoute,
  OauthInstagramCallbackClienteRoute: OauthInstagramCallbackClienteRoute,
  PlanejamentoTokenRoute: PlanejamentoTokenRoute,
  PreviewTokenRoute: PreviewTokenRoute,
  PromoSlugRoute: PromoSlugRoute,
  RCodeRoute: RCodeRoute,
  SelecaoTokenRoute: SelecaoTokenRoute,
  ApiCronActivationNudgesRoute: ApiCronActivationNudgesRoute,
  ApiCronCheckAgencyReferralsRoute: ApiCronCheckAgencyReferralsRoute,
  ApiCronComputeAgencyRanksRoute: ApiCronComputeAgencyRanksRoute,
  ApiCronHouseDailyStatsRoute: ApiCronHouseDailyStatsRoute,
  ApiCronPublishFacebookRoute: ApiCronPublishFacebookRoute,
  ApiCronPublishInstagramRoute: ApiCronPublishInstagramRoute,
  ApiCronPublishLinkedinRoute: ApiCronPublishLinkedinRoute,
  ApiCronPublishTiktokRoute: ApiCronPublishTiktokRoute,
  ApiCronRefreshInstagramTokensRoute: ApiCronRefreshInstagramTokensRoute,
  ApiCronRetentionCleanupRoute: ApiCronRetentionCleanupRoute,
  ApiCronSendAutomationEmailsRoute: ApiCronSendAutomationEmailsRoute,
  ApiCronSendPushNotificationsRoute: ApiCronSendPushNotificationsRoute,
  ApiCronSnapshotInstagramFollowersRoute:
    ApiCronSnapshotInstagramFollowersRoute,
  ApiDescadastrarTokenRoute: ApiDescadastrarTokenRoute,
  ApiIgMediaTokenRoute: ApiIgMediaTokenRoute,
  ApiSelecaoOgTokenRoute: ApiSelecaoOgTokenRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiSelecaoDownloadTokenFileIdRoute: ApiSelecaoDownloadTokenFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
