/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as OauthGoogleCalendarCallbackRouteImport } from './routes/oauth.google-calendar-callback'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhasTarefasRouteImport } from './routes/_authenticated/minhas-tarefas'
import { Route as AuthenticatedLimpezaRouteImport } from './routes/_authenticated/limpeza'
import { Route as AuthenticatedInvestigacaoRouteImport } from './routes/_authenticated/investigacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClienteClientIdRouteImport } from './routes/_authenticated/cliente.$clientId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarCallbackRoute =
  OauthGoogleCalendarCallbackRouteImport.update({
    id: '/oauth/google-calendar-callback',
    path: '/oauth/google-calendar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasTarefasRoute =
  AuthenticatedMinhasTarefasRouteImport.update({
    id: '/minhas-tarefas',
    path: '/minhas-tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLimpezaRoute = AuthenticatedLimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigacaoRoute =
  AuthenticatedInvestigacaoRouteImport.update({
    id: '/investigacao',
    path: '/investigacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteClientIdRoute =
  AuthenticatedClienteClientIdRouteImport.update({
    id: '/cliente/$clientId',
    path: '/cliente/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/limpeza': typeof AuthenticatedLimpezaRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/oauth/google-calendar-callback': typeof OauthGoogleCalendarCallbackRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/limpeza': typeof AuthenticatedLimpezaRoute
  '/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/oauth/google-calendar-callback': typeof OauthGoogleCalendarCallbackRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/investigacao': typeof AuthenticatedInvestigacaoRoute
  '/_authenticated/limpeza': typeof AuthenticatedLimpezaRoute
  '/_authenticated/minhas-tarefas': typeof AuthenticatedMinhasTarefasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRoute
  '/oauth/google-calendar-callback': typeof OauthGoogleCalendarCallbackRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cliente/$clientId': typeof AuthenticatedClienteClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/configuracoes'
    | '/investigacao'
    | '/limpeza'
    | '/minhas-tarefas'
    | '/perfil'
    | '/stories'
    | '/oauth/google-calendar-callback'
    | '/preview/$token'
    | '/cliente/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/configuracoes'
    | '/investigacao'
    | '/limpeza'
    | '/minhas-tarefas'
    | '/perfil'
    | '/stories'
    | '/oauth/google-calendar-callback'
    | '/preview/$token'
    | '/'
    | '/cliente/$clientId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/configuracoes'
    | '/_authenticated/investigacao'
    | '/_authenticated/limpeza'
    | '/_authenticated/minhas-tarefas'
    | '/_authenticated/perfil'
    | '/_authenticated/stories'
    | '/oauth/google-calendar-callback'
    | '/preview/$token'
    | '/_authenticated/'
    | '/_authenticated/cliente/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OauthGoogleCalendarCallbackRoute: typeof OauthGoogleCalendarCallbackRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar-callback': {
      id: '/oauth/google-calendar-callback'
      path: '/oauth/google-calendar-callback'
      fullPath: '/oauth/google-calendar-callback'
      preLoaderRoute: typeof OauthGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-tarefas': {
      id: '/_authenticated/minhas-tarefas'
      path: '/minhas-tarefas'
      fullPath: '/minhas-tarefas'
      preLoaderRoute: typeof AuthenticatedMinhasTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/limpeza': {
      id: '/_authenticated/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof AuthenticatedLimpezaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigacao': {
      id: '/_authenticated/investigacao'
      path: '/investigacao'
      fullPath: '/investigacao'
      preLoaderRoute: typeof AuthenticatedInvestigacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente/$clientId': {
      id: '/_authenticated/cliente/$clientId'
      path: '/cliente/$clientId'
      fullPath: '/cliente/$clientId'
      preLoaderRoute: typeof AuthenticatedClienteClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedInvestigacaoRoute: typeof AuthenticatedInvestigacaoRoute
  AuthenticatedLimpezaRoute: typeof AuthenticatedLimpezaRoute
  AuthenticatedMinhasTarefasRoute: typeof AuthenticatedMinhasTarefasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClienteClientIdRoute: typeof AuthenticatedClienteClientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedInvestigacaoRoute: AuthenticatedInvestigacaoRoute,
  AuthenticatedLimpezaRoute: AuthenticatedLimpezaRoute,
  AuthenticatedMinhasTarefasRoute: AuthenticatedMinhasTarefasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClienteClientIdRoute: AuthenticatedClienteClientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OauthGoogleCalendarCallbackRoute: OauthGoogleCalendarCallbackRoute,
  PreviewTokenRoute: PreviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
