
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'PLANEJAMENTO';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'COPY';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'REVISAO_INTERNA';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'AGENDAMENTO';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'REVISAO_AGENDAMENTO';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'EM_GRAVACAO';
ALTER TYPE public.content_status ADD VALUE IF NOT EXISTS 'EM_EDICAO';
